name: Build & Publish RSS (trybunalski)

on:
  schedule:
    - cron: "0 * * * *"   # co godzinę o pełnej godzinie (UTC)
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - "scraper.py"
      - "requirements.txt"
      - ".github/workflows/rss.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # potrzebne do pushowania zmian

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python scraper.py

      - name: Commit & push feed.xml
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add feed.xml
          git commit -m "Update feed.xml [skip ci]" || echo "No changes to commit"
          git push
